/**
 * 杭州云霁科技有限公司
 * http://www.idcos.com
 * Copyright (c) 2015-2017 All Rights Reserved.
 */
 
package com.idcos.gaunbin.dal.auto.dao.guan;

// auto generated imports
import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.gaunbin.dal.auto.dataobject.guan.DcosLogDO;
import org.springframework.stereotype.Repository;
/**
 * 自动生成DcosLogDAO
 *
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2018-04-25 16:31:05.
 * @author system-user
 * @version DcosLogDAO.java,v 1.1 2018-04-25 16:31:05 system-user Exp $
 */
@Repository
public interface DcosLogDAO extends BaseRepository<DcosLogDO, String> {


	/**  <p>
	 *  The jql statement for this operation is <br>
	 *	@param methodName
	 *	@return DcosProjectDO
	 */
	public DcosLogDO findByMethodName(String methodName);

}