/**
 * 杭州云霁科技有限公司
 * http://www.idcos.com
 * Copyright (c) 2015-2017 All Rights Reserved.
 */
 
package com.idcos.gaunbin.dal.auto.dao.guan;

// auto generated imports
import com.idcos.cloud.core.dal.common.jpa.BaseRepository;
import com.idcos.gaunbin.dal.auto.dataobject.guan.GuanTestDO;
import org.springframework.stereotype.Repository;
/**
 * 自动生成GuanTestDAO
 *
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2017-09-12 17:52:32.
 * @author system-user
 * @version GuanTestDAO.java,v 1.1 2017-09-12 17:52:32 system-user Exp $
 */
@Repository
public interface GuanTestDAO extends BaseRepository<GuanTestDO, String> {

}