/**
 * 杭州云霁科技有限公司
 * http://www.idcos.com
 * Copyright (c) 2015-2017 All Rights Reserved.
 */

package com.idcos.guanbin.web.controller.auto.guan;

// auto generated imports

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.idcos.cloud.biz.common.permisson.OperateAction;
import com.idcos.cloud.web.common.BaseResultVO;
import com.idcos.cloud.web.common.JsonResultUtil;
import com.idcos.guanbin.biz.guan.manager.auto.GuanTestOperateManager;
import com.idcos.guanbin.biz.guan.manager.auto.GuanTestQueryManager;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

/**
 * 主机计费信息接口
 * web层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2017-09-12 16:03:34.
 * @author GuanBin
 * @version GuanTestController.java,v 1.1 2017-09-12 16:03:34 GuanBin Exp $
 */

@Controller
@OperateAction("F_GUAN_TEST")
@Api(tags = "主机计费信息接口")
@RequestMapping(value = "/api/v1/guan/test")
public class GuanTestController {

    //========== manager ==========

    @Autowired
    private GuanTestQueryManager   guanTestQueryManager;

    @Autowired
    private GuanTestOperateManager guanTestOperateManager;

    /**  
     * 根据id查询计费信息
     *	@param id
     *	@return BaseResultVO
     */
    @RequestMapping(method = RequestMethod.GET, value = "/{id}")
    @ResponseBody
    @ApiOperation(value = "根据id查询计费信息", notes = "根据id查询计费信息")
    @OperateAction("O_GUAN_TEST_GET")
    public BaseResultVO queryById(@PathVariable String id) {
        return JsonResultUtil.getResult(guanTestQueryManager.queryById(id));

    }

    /**  
     * 删除计费信息
     *	@param id
     *	@return BaseResultVO
     */
    @RequestMapping(method = RequestMethod.DELETE, value = "/{id}")
    @ResponseBody
    @ApiOperation(value = "删除计费信息", notes = "删除计费信息")
    @OperateAction("O_GUAN_TEST_DELETE")
    public BaseResultVO delete(@PathVariable String id) {
        return JsonResultUtil.getResult(guanTestOperateManager.delete(id));

    }

    /**  
     * 查询所有主机计费信息
     *	@return BaseResultVO
     */
    @RequestMapping(method = RequestMethod.GET, value = "/all")
    @ResponseBody
    @ApiOperation(value = "查询所有主机计费信息", notes = "查询所有主机计费信息")
    @OperateAction("O_GUAN_TEST_GET")
    public BaseResultVO queryAll() {
        return JsonResultUtil.getResult(guanTestQueryManager.queryAll());

    }

}
