/**
 * 杭州云霁科技有限公司
 * http://www.idcos.com
 * Copyright (c) 2015-2017 All Rights Reserved.
 */
 
package com.idcos.gaunbin.dal.auto.dataobject.guan;

// auto generated imports
import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2018-04-25 16:31:06.
 * @author system-user
 * @version com.idcos.gaunbin.dal.auto.dataobject.guan.java,v 1.1 2018-04-25 16:31:06 system-user Exp $
 */
 
@Entity
@Table(name = "DCOS_LOG")
@EntityListeners(AuditingEntityListener.class)
public class DcosLogDO extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========
	/**
	* 数据库字段 <tt>ID</tt>.
	*/
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid2")
	@Column(name = "ID")
	@ColumnMeta(name = "ID", length = 64, description = "", pk = true, unique = false, nullable = false, scale = 0)
	private String id;

	/**
	* 数据库字段 <tt>METHOD_NAME</tt>.
	*/
	@Column(name = "METHOD_NAME")
	@ColumnMeta(name = "METHOD_NAME", length = 64, description = "", pk = false, unique = false, nullable = false, scale = 0)
	private String methodName;

	/**
	* 数据库字段 <tt>TIME</tt>.
	*/
	@Column(name = "TIME")
	@ColumnMeta(name = "TIME", length = 64, description = "", pk = false, unique = false, nullable = false, scale = 0)
	private String time;

	/**
	* 数据库字段 <tt>CREATE_USER_ID</tt>.
	*/
	@Column(name = "CREATE_USER_ID")
	@ColumnMeta(name = "CREATE_USER_ID", length = 64, description = "创建人", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.CreatedBy
	private String createUserId;

	/**
	* 数据库字段 <tt>GMT_CREATE</tt>.
	*/
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GMT_CREATE")
	@ColumnMeta(name = "GMT_CREATE", length = 19, description = "创建日期", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.CreatedDate
	private Date gmtCreate;

	/**
	* 数据库字段 <tt>MODIFY_USER_ID</tt>.
	*/
	@Column(name = "MODIFY_USER_ID")
	@ColumnMeta(name = "MODIFY_USER_ID", length = 64, description = "修改人", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.LastModifiedBy
	private String modifyUserId;

	/**
	* 数据库字段 <tt>GMT_MODIFIED</tt>.
	*/
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GMT_MODIFIED")
	@ColumnMeta(name = "GMT_MODIFIED", length = 19, description = "修改日期", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.LastModifiedDate
	private Date gmtModified;


    //========== getters and setters ==========

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public String getMethodName() {
		return methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}


	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}


	public String getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}


	public Date getGmtCreate() {
		return gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}


	public String getModifyUserId() {
		return modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}


	public Date getGmtModified() {
		return gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}



}
