/**
 * 杭州云霁科技有限公司
 * http://www.idcos.com
 * Copyright (c) 2015-2017 All Rights Reserved.
 */
 
package com.idcos.gaunbin.dal.auto.dataobject.guan;

// auto generated imports
import com.idcos.cloud.core.common.BaseVO;
import com.idcos.cloud.core.dal.common.ColumnMeta;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * 数据库配置文件自动生成,此文件属于自动生成的,具体可以参考codegen工程
 * Generated by <tt>jap-codgen</tt> on 2017-09-12 17:52:32.
 * @author system-user
 * @version com.idcos.gaunbin.dal.auto.dataobject.guan.java,v 1.1 2017-09-12 17:52:32 system-user Exp $
 */
 
@Entity
@Table(name = "GUAN_TEST")
@EntityListeners(AuditingEntityListener.class)
public class GuanTestDO extends BaseVO implements Serializable {

    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========
	/**
	* 数据库字段 <tt>ID</tt>.
	*/
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid2")
	@Column(name = "ID")
	@ColumnMeta(name = "ID", length = 64, description = "计费ID", pk = true, unique = false, nullable = false, scale = 0)
	private String id;

	/**
	* 数据库字段 <tt>PROJECT_ID</tt>.
	*/
	@Column(name = "PROJECT_ID")
	@ColumnMeta(name = "PROJECT_ID", length = 64, description = "项目ID", pk = false, unique = false, nullable = false, scale = 0)
	private String projectId;

	/**
	* 数据库字段 <tt>PROJECT_NAME</tt>.
	*/
	@Column(name = "PROJECT_NAME")
	@ColumnMeta(name = "PROJECT_NAME", length = 64, description = "项目名称", pk = false, unique = false, nullable = false, scale = 0)
	private String projectName;

	/**
	* 数据库字段 <tt>RES_TYPE_CODE</tt>.
	*/
	@Column(name = "RES_TYPE_CODE")
	@ColumnMeta(name = "RES_TYPE_CODE", length = 64, description = "资源类型", pk = false, unique = false, nullable = false, scale = 0)
	private String resTypeCode;

	/**
	* 数据库字段 <tt>RES_ID</tt>.
	*/
	@Column(name = "RES_ID")
	@ColumnMeta(name = "RES_ID", length = 64, description = "资源ID", pk = false, unique = false, nullable = false, scale = 0)
	private String resId;

	/**
	* 数据库字段 <tt>TOTAL_PRICE</tt>.
	*/
	@Column(name = "TOTAL_PRICE")
	@ColumnMeta(name = "TOTAL_PRICE", length = 64, description = "每天的计费价格", pk = false, unique = false, nullable = false, scale = 0)
	private String totalPrice;

	/**
	* 数据库字段 <tt>CREATE_USER_ID</tt>.
	*/
	@Column(name = "CREATE_USER_ID")
	@ColumnMeta(name = "CREATE_USER_ID", length = 64, description = "创建人", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.CreatedBy
	private String createUserId;

	/**
	* 数据库字段 <tt>GMT_CREATE</tt>.
	*/
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GMT_CREATE")
	@ColumnMeta(name = "GMT_CREATE", length = 19, description = "创建日期", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.CreatedDate
	private Date gmtCreate;

	/**
	* 数据库字段 <tt>MODIFY_USER_ID</tt>.
	*/
	@Column(name = "MODIFY_USER_ID")
	@ColumnMeta(name = "MODIFY_USER_ID", length = 64, description = "修改人", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.LastModifiedBy
	private String modifyUserId;

	/**
	* 数据库字段 <tt>GMT_MODIFIED</tt>.
	*/
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GMT_MODIFIED")
	@ColumnMeta(name = "GMT_MODIFIED", length = 19, description = "修改日期", pk = false, unique = false, nullable = false, scale = 0)
    @org.springframework.data.annotation.LastModifiedDate
	private Date gmtModified;


    //========== getters and setters ==========

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}


	public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}


	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}


	public String getResTypeCode() {
		return resTypeCode;
	}

	public void setResTypeCode(String resTypeCode) {
		this.resTypeCode = resTypeCode;
	}


	public String getResId() {
		return resId;
	}

	public void setResId(String resId) {
		this.resId = resId;
	}


	public String getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(String totalPrice) {
		this.totalPrice = totalPrice;
	}


	public String getCreateUserId() {
		return createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}


	public Date getGmtCreate() {
		return gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}


	public String getModifyUserId() {
		return modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}


	public Date getGmtModified() {
		return gmtModified;
	}

	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

}
