/**
 * 杭州云霁科技有限公司
 * http://www.idcos.com
 * Copyright (c) 2015-2017 All Rights Reserved.
 */
 
package com.idcos.guanbin.biz.guan.manager.auto;

// auto generated imports
import com.idcos.cloud.core.common.biz.CommonResult;

/**
 * manager层controller相关的接口自动生成，此文件属于自动生成的，请勿直接修改,具体可以参考codegen工程
 * Generated by <tt>controller-codegen</tt> on 2018-02-06 11:04:40.
 * @author GuanBin
 * @version GuanTestQueryManager.java,v 1.1 2018-02-06 11:04:40 GuanBin Exp $
 */
public interface GuanTestQueryManager  {


	/**  
	 * 根据id查询计费信息
	 *	@param id
	 *	@return BaseResultVO
	 */
	public CommonResult<?> queryById(String id);


	/**  
	 * 查询所有主机计费信息
	 *	@return BaseResultVO
	 */
	public CommonResult<?> getAll();


	/**  
	 * 异常接口
	 *	@return BaseResultVO
	 */
	public CommonResult<?> doError();


}